init:    
    image weet cred = "weet/portcred.jpg"
    image e amazora02 = "e/amazora02.jpg"
    image e amazora03 = "e/amazora03.jpg"
    image e b = "e/b.jpg"
    image e byoin7_rouka = "e/byoin7_rouka.jpg"
    image e byoin_chusyajo = "e/byoin_chusyajo.jpg"
    image e byoin_heya_yu2 = "e/byoin_heya_yu2.jpg"
    image e byoin_rouka = "e/byoin_rouka.jpg"
    image e c00 = "e/c00.jpg"
    image e c001 = "e/c001.jpg"
    image e c002 = "e/c002.jpg"
    image e c02 = "e/c02.jpg"
    image e c02b = "e/c02b.jpg"
    image e c003 = "e/c003.jpg"
    image e c03 = "e/c03.jpg"
    image e c004 = "e/c004.jpg"
    image e c04 = "e/c04.jpg"
    image e c04_h = "e/c04_h.jpg"
    image e c005 = "e/c005.jpg"
    image e c032 = "e/c032.jpg"
    image e c033 = "e/c033.jpg"
    image e c042 = "e/c042.jpg"
    image e c042_h = "e/c042_h.jpg"
    image e c043 = "e/c043.jpg"
    image e c043_h = "e/c043_h.jpg"
    image e c0052 = "e/c0052.jpg"
    image e car_byoin_chusyajo = "e/car_byoin_chusyajo.jpg"
    image e car_byoin_chusyajo_yoru = "e/car_byoin_chusyajo_yoru.jpg"
    image e car_byoin_chusyajo_yoru_ame = "e/car_byoin_chusyajo_yoru_ame.jpg"
    image e car_michi01 = "e/car_michi01.jpg"
    image e car_naname_michi01 = "e/car_naname_michi01.jpg"
    image e carkey = "e/carkey.jpg"
    image e chara_001 = "e/chara_001.jpg"
    image e chara_0012 = "e/chara_0012.jpg"
    image e chara_0013 = "e/chara_0013.jpg"
    image e chara_0013b = "e/chara_0013b.jpg"
    image e chara_k01 = "e/chara_k01.jpg"
    image e chara_k02 = "e/chara_k02.jpg"
    image e chusha_hamabe_yu = "e/chusha_hamabe_yu.jpg"
    image e chusha_michi2_yoru = "e/chusha_michi2_yoru.jpg"
    image e chusha_michi2_yu = "e/chusha_michi2_yu.jpg"
    image e chusha_michi_ame_yoru = "e/chusha_michi_ame_yoru.jpg"
    image e coin_tennai = "e/coin_tennai.jpg"
    image e danwa = "e/danwa.jpg"
    image e danwa_ame = "e/danwa_ame.jpg"
    image e danwa_yoru = "e/danwa_yoru.jpg"
    image e gs = "e/gs.jpg"
    image e hashigeta = "e/hashigeta.jpg"
    image e hiki_kosoku = "e/hiki_kosoku.jpg"
    image e hiki_kosoku2 = "e/hiki_kosoku2.jpg"
    image e hiki_shigai_yu = "e/hiki_shigai_yu.jpg"
    image e image01 = "e/image01.jpg"
    image e imege03 = "e/imege03.jpg"
    image e imege04 = "e/imege04.jpg"
    image e imege05 = "e/imege05.jpg"
    image e imege06 = "e/imege06.jpg"
    image e imege07 = "e/imege07.jpg"
    image e imege09 = "e/imege09.jpg"
    image e imege072 = "e/imege072.jpg"
    image e imege92 = "e/imege92.jpg"
    image e imege93 = "e/imege93.jpg"
    image e imege94 = "e/imege94.jpg"
    image e imege94_h = "e/imege94_h.jpg"
    image e imege95 = "e/imege95.jpg"
    image e imege95_h = "e/imege95_h.jpg"
    image e imege96 = "e/imege96.jpg"
    image e imege96_h = "e/imege96_h.jpg"
    image e imege97 = "e/imege97.jpg"
    image e imege97_h = "e/imege97_h.jpg"
    image e joku_kosoku = "e/joku_kosoku.jpg"
    image e joku_kosoku_yu = "e/joku_kosoku_yu.jpg"
    image e joku_shigachi = "e/joku_shigachi.jpg"
    image e naname_inaka_ame2 = "e/naname_inaka_ame2.jpg"
    image e naname_inaka_yoru = "e/naname_inaka_yoru.jpg"
    image e naname_inaka_yu = "e/naname_inaka_yu.jpg"
    image e naname_machi = "e/naname_machi.jpg"
    image e naname_machi2 = "e/naname_machi2.jpg"
    image e naname_machi2_yoru = "e/naname_machi2_yoru.jpg"
    image e naname_michi = "e/naname_michi.jpg"
    image e naname_michi_yoru = "e/naname_michi_yoru.jpg"
    image e naname_yuki = "e/naname_yuki.jpg"
    image e nar01 = "e/nar01.jpg"
    image e narcissu_b = "e/narcissu_b.jpg"
    image e narcissu_yoru_ame = "e/narcissu_yoru_ame.jpg"
    image e pachi = "e/pachi.jpg"
    image e setsumi_kaisou = "e/setsumi_kaisou.jpg"
    image e shanai_inaka = "e/shanai_inaka.jpg"
    image e shanai_michi01 = "e/shanai_michi01.jpg"
    image e shanai_michi01_yoru = "e/shanai_michi01_yoru.jpg"
    image e shanai_michi01_yu = "e/shanai_michi01_yu.jpg"
    image e shanai_michi01b = "e/shanai_michi01b.jpg"
    image e shanai_michi02_yoru = "e/shanai_michi02_yoru.jpg"
    image e shanai_michi03_yu = "e/shanai_michi03_yu.jpg"
    image e shanai_michi04 = "e/shanai_michi04.jpg"
    image e sora01 = "e/sora01.jpg"
    image e sora02 = "e/sora02.jpg"
    image e sora03 = "e/sora03.jpg"
    image e sora06 = "e/sora06.jpg"
    image e sora07 = "e/sora07.jpg"
    image e sora_ame01 = "e/sora_ame01.jpg"
    image e sora_ame01b = "e/sora_ame01b.jpg"
    image e sora_ame02 = "e/sora_ame02.jpg"
    image e sora_ame03 = "e/sora_ame03.jpg"
    image e sora_yoru01 = "e/sora_yoru01.jpg"
    image e sora_yu = "e/sora_yu.jpg"
    image e soukou = "e/soukou.jpg"
    image e soukou_machi = "e/soukou_machi.jpg"
    image e soukou_machi_yoru = "e/soukou_machi_yoru.jpg"
    image e soukou_machi_yu = "e/soukou_machi_yu.jpg"
    image e soukou_yoru = "e/soukou_yoru.jpg"
    image e st00 = "e/st00.jpg"
    image e st01 = "e/st01.jpg"
    image e st02 = "e/st02.jpg"
    image e st03 = "e/st03.jpg"
    image e st04 = "e/st04.jpg"
    image e st05 = "e/st05.jpg"
    image e st06 = "e/st06.jpg"
    image e st07 = "e/st07.jpg"
    image e st08 = "e/st08.jpg"
    image e st09 = "e/st09.jpg"
    image e tv_hana = "e/tv_hana.jpg"
    image e umibe_yoru = "e/umibe_yoru.jpg"
    image e w = "e/w.jpg"
    image e yakkyoku = "e/yakkyoku.jpg"
    image e yuki_kohan = "e/yuki_kohan.jpg"
    image e yukizora = "e/yukizora.jpg"
    image tui2 c044 = "tui2/c044.jpg"
    image tui2 c044_h = "tui2/c044_h.jpg"
    image tui2 c045 = "tui2/c045.jpg"
    image tui2 c046 = "tui2/c046.jpg"
    image tui2 c047 = "tui2/c047.jpg"
    image tui2 c048 = "tui2/c048.jpg"
    image tui2 c049 = "tui2/c049.jpg"
    image tui2 c0432 = "tui2/c0432.jpg"
    image tui2 c0432_h = "tui2/c0432_h.jpg"
    image tui2 c0442 = "tui2/c0442.jpg"
    image tui2 cat02 = "tui2/cat02.jpg"
    image tui2 cat02_h = "tui2/cat02_h.jpg"
    image tui2 cat03 = "tui2/cat03.jpg"
    image tui2 cat03_h = "tui2/cat03_h.jpg"
    image tui2 cat05 = "tui2/cat05.jpg"
    image tui2 cat06 = "tui2/cat06.jpg"
    image tui2 cat07 = "tui2/cat07.jpg"
    image tui2 cat072 = "tui2/cat072.jpg"
    image tui2 cat072_h = "tui2/cat072_h.jpg"
    image tui2 cat073 = "tui2/cat073.jpg"
    image tui2 cat073_h = "tui2/cat073_h.jpg"
    image yobi car_byoin_chusyajo_yu = "yobi/car_byoin_chusyajo_yu.jpg"
	image yobi cat02 = "yobi/cat02.jpg"
	image yobi cat02_h = "yobi/cat02_h.jpg"
	image yobi cat03 = "yobi/cat03.jpg"
	image yobi cat03_h = "yobi/cat03_h.jpg"
	image yobi cat05 = "yobi/cat05.jpg"
	image yobi cat05_h = "yobi/cat05_h.jpg"
	image yobi cat06 = "yobi/cat06.jpg"
	image yobi cat07 = "yobi/cat07.jpg"
	image yobi cat09 = "yobi/cat09.jpg"
	image yobi cat09_h = "yobi/cat09_h.jpg"
	define se = Character('Setsumi')
	define w = Character('???')
label start:
    "Note: The English Version of 'Narcissu' contains two different translations: One from the voiced version (by Seung Park, a.k.a. gp32); One from the unvoiced version (by Peter Jolly, a.k.a. Haeleth)."
    "Select a version which you most prefer."
    menu:
        "gp32":
            $renpy.block_rollback()
            "DISCLAIMER: The character vocals have been temporarily disabled in this version of the game's port as it may interfere with the performance of the RenPSP Visual Novel engine." "Press X to Continue"
            scene weet cred
            $renpy.pause(2)
            jump GP_prologue
        "Haeleth":
            $renpy.block_rollback()
            scene weet cred
            $renpy.pause(2)
            jump HAE_prologue
label GP_prologue:
    jump quit
label HAE_prologue:
	scene e b
	$renpy.pause(1)
	scene e c001
	$renpy.pause(0.4)
	scene e c002
	$renpy.pause(0.4)
	scene e c003
	$renpy.pause(0.7)
	scene e c004
	""
	play sound "se/rain_1.wav"
	scene e c02
	"- Spring 1996 : Setsumi -"
	play music "bgm/n04.ogg"
	scene e sora_ame01
	"\"My health was never particularly good, sure...\""
	"But I was able to attend primary school like anyone else." "In the summer holidays I was able to play till the sun burnt me black."
	scene e byoin_heya_yu2
	"It was June, just after I entered middle school." "" "It was just before the midterm tests."
	"It was the day after I ordered a swimming costume for the summer." "That was the first day I was admitted to hospital."
	"It was a cold, unpleasant, drizzly day."
	play sound "se/rain_1.wav"
	scene e sora_ame03
	"Shrouded by the rainy sky, murky, white, and damp."
	"At first my classmates came to see me every day."
	"When I was out of hospital, they'd come over to play at the weekend."
	"But that was only at first."
	scene e sora_ame01
	"Autumn came, and passed into winter." "I was admitted, and discharged; went in for tests, and was readmitted..."
	"There were people in my class that I'd called my friends."
	"Before I'd really realised what was happening, they were merely acquaintances."
	"Then strangers."
	"With each change of the seasons, I faded from more memories."
	scene e chara_k01
	"\"I suppose they... don't like seeing me.\""
	$renpy.pause(0.3)
	"\"If you've got a normal life, you don't want someone like me in it...\""
	"\"So they blank me out...\""
	play sound "se/rain_1.wav"
	scene e w
	$renpy.pause(0.4)
	scene e sora_ame03
	"\"I've passed all these seasons, under that white overcast sky, without needing to speak to anyone...\""
	"\"My English textbook is untouched from the first-year midterms onwards...\""
	scene e chara_0012
	"\"As though..."
	"\"As though..." "even time stopped for me there...\""
	play sound "se/z42r.wav"
	scene e w
	$renpy.pause(0.8)
	scene e c00
	"Eight years later" "- Early Summer 2004 : Protagonist -"
	scene e sora01
	"It was summer. The sweaty season."
	"We were all staring intently at the display board."
	"This test centre was pretty up-to-date; the display was computerised."
	"The lights on it, the indicators of success, were beginning to come on."
	"We were all watching for our own numbers."
	"'237... 237...'"
	"About 80% of the lights flickered on. My number was among them."
	scene e b
	play sound "se/faan1_b.wav"
	"I took the train home." "It was a quiet time of day; the rattling, swaying carriage was practically empty."
	"In my left hand, the copy of the Highway Code they gave me." "In my breast pocket, a brand-new driving licence."
	"\"So now I'm a driver too...\""
	"I tried to whisper it as though it were a profound thing, but it didn't actually excite me all that much."
	"I hadn't particularly wanted to be able to drive." "It wasn't that I'd had any other motive for taking the test... I was just doing what all my friends were doing."
	scene e sora_yoru01
	"That night."
	"I told my parents I'd got a licence." "All they said was, \"well done\"."
	"I tried asking to borrow the car, just to see what would happen." "All they said was,"
	"I tried asking to borrow the car, just to see what would happen." "All they said was, \"not now\"."
	"I hadn't been expecting anything else. It was an entirely predictable response." "That's just the kind of parents I have."
	scene e b
	"The next day I woke up with an excruciating pain in my chest." "Bad enough that I took it straight to hospital."
	"I wasn't particularly well acquainted with the place at that time." "There was a long wait to be seen. Long and tedious."
	scene e byoin_rouka
	"When at last they straightened up, I thought the examination was over." "Then it turned out I was going... being taken... for X-rays and blood tests."
	"Then there was another long, long wait..."
	"I read three whole issues of \"Jump\" in the waiting room that day." "Then, as I reached out for the fourth..."
	"...they came and took me away."
	"My brand new driving licence was still in my breast pocket."
	"Apparently I wasn't going to have a chance to use that quite yet..."
	scene e b
	play music "bgm/blank.ogg"
	scene e sora07
	$renpy.pause(0.8)
	scene e c03
	"- Autumn 2004 -"
	play music "tui2/e01.ogg"
	scene e sora07
	"It was about the time of year when the cicadas finally start to shut up."
	"I was in hospital, as usual."
	"Oh, I hadn't been in there all summer."
	"I'd been in and out, back and forth, on and off."
	"I'd had my first operation the previous month. They'd discharged me afterwards, but I still had to go back in a lot." "Thankfully it was only five minutes by moped."
	"And so the cycle continued: admission, discharge, tests, readmission, and on, and on, and on..."
	"Whether it was for PET scans or for Iressa treatment, I don't know, but before I knew it, the cycle had been going on for months."
	"My appetite shrank, while the number of medicines I was expected to swallow just kept on increasing." "I felt like I could literally see myself getting weaker."
	"Even my legs seemed to be withering."
	"It wasn't my imagination." "I would weigh myself, and the needle of the scales would confirm it."
	"And yet..."
	"And yet..." "somehow it didn't really seem all that personal."
	"It was like I was watching it happen to somebody else." "Like it was just a scene from some TV drama."
	"I was unable to understand what was happening to my body all of a sudden." "I hadn't even grasped that the changes were real."
	"So though it was as personal as anything could be, still I could only observe it as though from a far and disinterested position."
	scene e c033
	""
	scene e b
	"A winter's day." "It was the time of year when municipal Christmas decorations are dismantled."
	"They let me go home for New Year."
	"It was only a temporary thing, but it was a welcome change."
	scene e amazora02
	"I arrived home amidst sleet and driving rain."
	"For some reason the whole family was there to greet me."
	"My parents had always been quiet and aloof." "Today they greeted me with smiles and laughter, though it seemed forced."
	"My sister had never had anything for me but a sharp tongue." "Today she had made me my favourite cream stew with fried prawns."
	"We sat around the kotatsu. She peeled me a satsuma." "I was touched to be treated with such unusual kindness."
	"It was then that I began to realise."
	"That unused driving licence, still in my pocket..."
	"I began to realise that I was probably not going to get much use out of it."
	scene e w
	"That's what I thought, as the forced smiles and false cheer washed over me."
	"That's all I thought, in the same calm, vague, detached way I'd been thinking about this whole affair."
	scene e c032
	"- January 2005 -"
	scene e byoin_rouka
	"I returned to hospital in the new year."
	"For once I didn't return straight to the fourth floor." "Instead I went... was taken... to a different room, a discussion room."
	"My father was with me, and there was a doctor as well." "They talked to me, or rather at me. I listened. Was made to listen."
	"It turned out that this was what they call \"disclosure\"."
	"The doctor took a long time to explain everything, and used a lot of long words in the process, as doctors do."
	"But all it came down to was, it looked like I was going to die."
	"\"Oh...\""
	"I couldn't think of anything else to say." "That was the only sound I uttered from the moment I entered the room till the moment I left it."
	"Apparently that was a good enough response." "The doctor produced a biro and began scribbling."
	"The formalities this time revolved around admitting me into the hospice ward." "The doctor had switched into business mode. My father did the same."
	"As for me, all I could do was sit and be amazed at the efficiency of the proceedings."
	scene e b
	"They moved me from the fourth floor to the seventh, and from a six-bed ward to a private room."
	scene e byoin7_rouka
	"The seventh floor differed from the others in a number of respects."
	"The floors gleamed. The ceiling was higher, the rooms more spacious than before."
	"The bedrooms were pleasant and clean, with large windows designed to maximise the natural lighting."
	"But these windows were not designed to open."
	"When pushed to their fullest extent, the gap was still so narrow that I couldn't even get my head quite through it."
	"One other thing was different: the colour of the patients' identification wristbands."
	"I'd been wearing one of these ever since I was first admitted to the hospital." "They were just plastic bands with the patient's name and blood group on them."
	"My old one had been blue. This one was white."
	scene e b
	"That was my introduction to the seventh floor: high ceilings, white wristbands, and windows that only opened about 15 centimetres."
	"It was still the time of year when all you can get on TV is boring festive programmes."
	"That, in a way, is how I came to meet her..."
	play music "bgm/blank.ogg"
	scene e w
	$renpy.pause(0.6)
	scene e nar01
	""
	scene e w
	#jump HAE_honpen2
label quit:
    $renpy.quit()
